- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/Layout/Contents/Contents.tsx
- client/src/Layout/Footer/Footer.tsx
- client/src/Layout/GeneraLayout.tsx
- client/src/Layout/Header/GNB.tsx
- client/src/Layout/Header/Header.tsx
- client/src/Page/Main.tsx
- client/src/Page/signUp.tsx
- client/src/router.tsx
fe/router => def-FE
- 기본 라우터 설정 완료.
- 이후 페이지 추가는 client 루트 폴더의 router.tsx 를 참고해주세요.
- Header, Footer 기본 CSS 설정.
> [Layout / Feat] 기본 Router 설정

- client/src/App.tsx
- client/src/Components/Main/Explan.tsx
- client/src/Components/Main/Info.tsx
- client/src/Components/Main/Member.tsx
- client/src/Components/Main/Peacock.tsx
- client/src/Page/Main.tsx
- client/src/react-app-env.d.ts
- client/src/router.tsx
- 메인 풀페이지 구현
- router에 chatting과 chatlist 연결
> [feat] 메인페이지

- client/src/Components/User/AddPet.tsx
- client/src/Components/User/MyLikes.tsx
- client/src/Components/User/MyPets.tsx
- client/src/Components/User/MyPost.tsx
- client/src/Components/User/PetCard.tsx
- client/src/Components/User/UserInfo.tsx
- client/src/Page/User.tsx
- 유저 페이지 기본 구성
- 작성한 게시글 / 좋아요 컴포넌트 내부는 추후 추가 예정
> [design] 유저 페이지 기본 레이아웃 구성

- client/package-lock.json
- client/package.json
- client/src/Hook/useGetMainData.ts
- client/src/index.tsx
- react-query 세팅
- 메인 페이지에 react-query 임시 적용
> [feat] main페이지 react-query 임시 적용

- client/package-lock.json
- client/package.json
- client/src/Components/User/UserInfo.tsx
- client/src/Hook/useGetUserProfile.ts
- client/src/Page/User.tsx
- client/tailwind.config.js
- react-query userInfo 임의 적용
- userInfo react-icons 적용
- tailwind 커스텀 색상 변경
> [feat] react-query UserInfo 임의 적용

- client/src/Components/User/AddPet.tsx
- client/src/Components/User/PetCard.tsx
- client/src/Components/User/UserInfo.tsx
- 유저 이미지 변경 함수 적용
- 마이펫 관련 입력 항목 추가
> [feat] 마이펫 항목 추가

- client/src/Components/User/UserInfo.tsx
- client/src/Hook/useDeleteUserProfile.ts
- client/src/Hook/useGetUserProfile.ts
- client/src/Hook/usePatchUserProfile.ts
- 회원정보 조회 기능 구현
- 회원정보 수정 기능 구현
- 회원탈퇴 기능 구현
> [feat] UserProfile 기능 구현

- client/src/Components/User/MyPets.tsx
- client/src/Components/User/PetCard.tsx
- client/src/Hook/usePatchMyPet.ts
- 마이펫 이미지 수정 기능 구현
- 마이펫 수정 데이터 연결
- 마이펫 수정 훅 연결
> [feat] MyPet 수정 기능 구현

- client/src/Components/Main/Explan.tsx
- client/src/Components/Main/Info.tsx
- client/src/Components/Main/MainPeacock.tsx
- client/src/Hook/useGetMainData.ts
- 메인페이지 자랑하기 페이지의 사진 데이터 연결
- 메인페이지의 버튼에 각 페이지 이동 함수 연결
> [feat] Main 페이지 데이터 연결, router 버튼 연결

- server/src/main/java/com/Petching/petching/board/controller/BoardController.java
- server/src/main/java/com/Petching/petching/board/dto/BoardDto.java
- server/src/main/java/com/Petching/petching/board/entity/Board.java
- server/src/main/java/com/Petching/petching/global/api/s3/controller/S3Controller.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/UserControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
- server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
- server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
: Ing -> 기초 틀 잡음, BoardController 메서드  중 POST만 통과된 상태입니다.
> [feat] Rest Docs API 문서화 - BoardController

- server/src/docs/asciidoc/index.adoc
- server/src/main/java/com/Petching/petching/global/aws/s3/service/S3Service.java
: S3Client 인스턴스를 계속 만들고 삭제하는 방식으로 변경,
index.adoc 에 board-post 추가
> [refactor] S3Service, index.adoc 수정

- client/src/Components/Main/MainPeacock.tsx
- client/src/Hook/useGetMainData.ts
- 메인페이지 자랑하기 데이터 변경 형식 적용
- 받아오는 데이터 타입 변경 : string[] => {
ImgUrls: string[];
}
> [refactor] MainData 변경된 형식 적용

- client/src/API/signUp.ts
- client/src/Components/Chatting/chattingComponent.tsx
- client/src/Components/Login/signUpComponent.tsx
- client/src/Util/types.ts
- server/index.js
[feat]signup password  일치시 알람문구와 color추가,
signUpData-password type 변경했습니다
> [feat]signup password  일치시 알람문구와 color추가

- client/src/Components/Care/Board.tsx
- client/src/Components/Care/Carousel.tsx
- client/src/Components/Care/TextEditor.tsx
- client/src/Page/CareList.tsx
> [feat] Board조회 데이터 불러오기 

- client/src/API/signIn.ts
- client/src/API/signUp.ts
> [refactor]url 주소 변경

- client/package-lock.json
- client/package.json
- client/src/Components/Login/signInComponent.tsx
- client/src/Components/Main/Explain.tsx
- client/src/Hook/useGetMyPets.ts
- client/src/Hook/useGetUserProfile.ts
- client/src/Layout/Header/GNB.tsx
- client/src/Page/Main.tsx
- client/src/Util/getUserIdFromToken.ts
- client/src/Util/types.ts
- client/src/store/login.ts
- Zustand 로그인 유무 전역관리 적용
- 토큰에서 userId 받아오는 코드 구현
- 로그인 유무에 따른 헤더 표시 변경
- navigate 연결
> [feat] 로그인 유무 헤더 반영

- server/src/docs/asciidoc/Comment-API.adoc
- server/src/docs/asciidoc/자랑하기-API.adoc
- server/src/main/java/com/Petching/petching/board/entity/Board.java
- server/src/main/java/com/Petching/petching/login/jwt/service/JwtService.java
- server/src/main/resources/static/docs/Comment-API.html
- server/src/main/resources/static/docs/S3-API.html
- server/src/main/resources/static/docs/User-API.html
- server/src/main/resources/static/docs/index.html
- server/src/main/resources/static/docs/자랑하기-API.html
- server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/CommentControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
- server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
- server/src/test/java/com/Petching/petching/restDocs/v1/comment/CommentControllerTest.java
- server/src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
: board controller, comment controller 테스트 코드 수정.
> [refactor] request 형태 token으로 변경으로 인한 API 문서 수정

- server/src/docs/asciidoc/CarePost-API.adoc
- server/src/docs/asciidoc/index.adoc
- server/src/docs/asciidoc/자랑하기-API.adoc
- server/src/main/resources/static/docs/Comment-API.html
- server/src/main/resources/static/docs/S3-API.html
- server/src/main/resources/static/docs/User-API.html
- server/src/main/resources/static/docs/index.html
- server/src/main/resources/static/docs/자랑하기-API.html
- server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
- server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
- server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
- server/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
- server/src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
- server/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
: CarePostController API 에 관한 테스트 코드 추가 및 API 문서 작성완료했습니다.
기존 API 문서에서 바뀐 부분, 잘못된 부분 수정했습니다.
> [feat] CarePostController API 문서, 기존 API 문서 수정.

- client/src/Components/User/AddPet.tsx
- client/src/Components/User/MyPets.tsx
- client/src/Components/User/PetCard.tsx
- client/src/Components/User/UserInfo.tsx
- client/src/Hook/useGetMyPets.ts
- client/src/Hook/useGetUserProfile.ts
- client/src/Hook/usePatchMyPet.ts
- client/src/Hook/usePatchUserProfile.ts
- client/src/Hook/usePostMyPet.ts
- client/src/Layout/Header/GNB.tsx
- 로그인 유무에 따른 헤더 반영
- 누락된 GNB 추가
- 유저 정보 조회 / 수정 업데이트
- 마이펫 관련 기능 구현
> [feat] 로그인 유무 반영 / MyPets 관련 기능 구현

- client/src/Components/peacockComponent.tsx
- client/src/Hook/useGetPeacock.ts
- client/src/Hook/usePostPeacock.ts
- client/src/Page/Peacock.tsx
- client/src/Page/peacockDetail.tsx
- client/src/Page/peacockWrite.tsx
- client/src/router.tsx
> [fe] usegetpeacock

- server/src/docs/asciidoc/CarePost-API.adoc
- server/src/docs/asciidoc/JWT-API.adoc
- server/src/docs/asciidoc/S3-API.adoc
- server/src/docs/asciidoc/index.adoc
- server/src/main/java/com/Petching/petching/carepost/controller/CarePostController.java
- server/src/main/java/com/Petching/petching/global/api/s3/controller/S3Controller.java
- server/src/main/java/com/Petching/petching/login/dto/LoginDto.java
- server/src/main/resources/static/docs/CarePost-API.html
- server/src/main/resources/static/docs/JWT-API.html
- server/src/main/resources/static/docs/S3-API.html
- server/src/main/resources/static/docs/User-API.html
- server/src/main/resources/static/docs/index.html
- server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/JwtControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/LoginTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
- server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
- server/src/test/java/com/Petching/petching/restDocs/v1/jwt/JwtControllerTest.java
- server/src/test/java/com/Petching/petching/restDocs/v1/login/LoginTest.java
아래의 목록을 추가했습니다.
- Acces token 재발급 API docs
- CarePost API refactoring, API docs
> [feat] Jwt, CarePost API DOCS

- client/src/Components/User/AddPet.tsx
- client/src/Components/User/MyPets.tsx
- client/src/Components/User/PetCard.tsx
- client/src/Components/User/UserInfo.tsx
- client/src/Hook/useDeleteMyPet.ts
- client/src/Hook/useGetMyPets.ts
- client/src/Hook/usePatchMyPet.ts
- client/src/Hook/usePatchUserProfile.ts
- client/src/Hook/usePostMyPet.ts
- client/src/Util/postImg.ts
- 이미지 url 반환 함수 구현(Util/postImg.ts)
- 유저 프로필 이미지 수정 기능 구현
- MyPet관련 CRUD 구현
> [feat] UserProfile 및 MyPets 관련 기능 구현

- server/src/main/java/com/Petching/petching/carepost/controller/CarePostController.java
- server/src/main/java/com/Petching/petching/carepost/service/CarePostService.java
- server/src/main/java/com/Petching/petching/user/controller/UserController.java
- server/src/main/java/com/Petching/petching/user/dto/CheckDto.java
- server/src/main/java/com/Petching/petching/user/dto/UserResponseDto.java
- server/src/main/java/com/Petching/petching/user/mapper/UserMapper.java
- server/src/main/java/com/Petching/petching/user/service/UserService.java
- User 조회 시 OAuth 유저 구분
- User 수정 비밀번호 변경 시 비밀번호 확인 로직 추가
- 마이페이지 회원이 작성한 펫 시터 글 조회
> [PR] back/ej to dev-back

- server/src/main/java/com/Petching/petching/global/api/s3/controller/S3Controller.java
- server/src/main/resources/static/docs/CarePost-API.html
- server/src/main/resources/static/docs/Comment-API.html
- server/src/main/resources/static/docs/JWT-API.html
- server/src/main/resources/static/docs/S3-API.html
- server/src/main/resources/static/docs/User-API.html
- server/src/main/resources/static/docs/index.html
- server/src/main/resources/static/docs/자랑하기-API.html
- server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/UserControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
- User Dto 수정으로 인한 테스트 코드 수정 
- S3 upload 엔드포인트 추가 : POST /api/s3/upload?uploadTo=boards
> [refactor] User Dto 수정으로 인한 테스트 코드 수정 및 S3 upload 엔드포인트 추가

- client/src/Hook/useDeleteMyPet.ts
- client/src/Hook/useDeleteUserProfile.ts
- client/src/Hook/useGetMyPets.ts
- client/src/Hook/useGetUserProfile.ts
- client/src/Hook/usePatchMyPet.ts
- client/src/Hook/usePatchUserProfile.ts
- client/src/Hook/usePostMyPet.ts
- client/src/Layout/Header/GNB.tsx
- GNB에 프로필 이미지가 뜨지 않는 현상 수정
- axios => Axios 변경
- 페이지 이동시 아이콘 닫기는 기능 추가
- 비로그인시 토큰값부재로 발생하는 오류 수정
> [fix] GNB 프로필 이미지가 뜨지 않는 현상 수정

- client/src/Layout/Header/GNB.tsx
> [fix] 로그인 헤더 변경 안되는 현상 수정

- client/src/API/user.ts
- client/src/Components/User/AddPet.tsx
- client/src/Components/User/MyPets.tsx
- client/src/Components/User/PetCard.tsx
- client/src/Components/User/UserInfo.tsx
- client/src/Hook/useGetUserProfile.ts
- client/src/Hook/usePatchUserProfile.ts
- client/src/Layout/Header/GNB.tsx
- client/src/Util/types.ts
- 비밀번호 변경 기능 구현
- submit 실행할 때만 이미지 url 요청이 가도록 변경
> [feat] 비밀번호 변경 기능 구현

- server/src/main/java/com/Petching/petching/carepost/controller/CarePostController.java
- server/src/main/java/com/Petching/petching/carepost/mapper/CarePostMapper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/UserControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
- server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
- server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
- User Delete 메서드, CarePost entity 및 dto 수정으로 인한 테스트 코드 수정
- S3 API 문서 일부 수정
> [refactor] User logic, CarePost entity 및 Dto 수정으로 인한 테스트 코드, API 문서 수정

- client/src/API/signUp.ts
- client/src/API/user.ts
- client/src/Components/User/Warning.tsx
- client/src/Hook/useDeleteMyPet.ts
- client/src/Hook/useDeleteUserProfile.ts
- client/src/Hook/useGetMyPets.ts
- client/src/Hook/useGetUserProfile.ts
- client/src/Hook/usePatchMyPet.ts
- client/src/Hook/usePatchUserProfile.ts
- client/src/Hook/usePostMyPet.ts
- client/src/Util/postImg.ts
- .env 경로 변경 REACT_APP_BASE_URL => REACT_APP_API_SERVER
> [refactor] .env 연결 변경

- client/src/Components/User/UserInfo.tsx
- client/src/Hook/useDeleteUserProfile.ts
- client/src/Layout/Header/GNB.tsx
- client/src/Util/getCookie.ts
- 로그아웃 / 회원탈퇴시 리프레시토큰 제거 로직 추가
- Util/getCookie.ts 에 removeCookie 함수 추가
> [refactor] 로그아웃/회원탈퇴시 쿠키(리프레시토큰)제거 로직 추가

- client/src/Components/Common/Warning.tsx
- client/src/Components/User/MyPets.tsx
- client/src/Components/User/PetCard.tsx
- client/src/Components/User/UserInfo.tsx
- client/src/Components/User/Warning.tsx
- 모달 컴포넌트 구현(Components/Common/Warning.tsx)
- 회원 탈퇴 / 펫카드 삭제시 모달창 연결
```jsx
interface WarningType {
title: string; // 모달 제목
sub: string; // 모달 내용
fn: () => void; // 확인 버튼을 클릭했을 때 실행되는 함수
setState: Dispatch<SetStateAction<boolean>>; // 모달창을 열고 닫는 setState
}
```
> [feat] 모달 컴포넌트 구현

- client/src/Components/User/AddPet.tsx
- client/src/Components/User/PetCard.tsx
- client/src/Components/User/UserInfo.tsx
- client/src/Util/postImg.ts
- 이미지 삭제 함수 구현
- Util/postImg.ts 파일 내 deleteImgHandler 함수
- UserInfo.tsx(회원정보 수정,삭제), PetCard(펫 정보 수정,삭제) 컴포넌트에 deleteImgHandler 함수 연결
> [feat] 이미지 삭제 함수 구현

- client/src/API/api.ts
- client/src/API/user.ts
- client/src/Hook/useDeleteMyPet.ts
- client/src/Hook/useDeleteUserProfile.ts
- client/src/Hook/useGetMainData.ts
- client/src/Hook/useGetMyPets.ts
- client/src/Hook/useGetMyPostToCare.ts
- client/src/Hook/useGetUserProfile.ts
- client/src/Hook/usePatchMyPet.ts
- client/src/Hook/usePatchUserProfile.ts
- client/src/Hook/usePostMyPet.ts
- client/src/Util/postImg.ts
- api.ts 의 const BASE_URL = process.env.REACT_APP_API_SERVER 코드에 export 적용
- 그 외 BASE_URL 사용하는 코드에 모두 import 적용
> [refactor] BASE_URL 관리 변경

- server/src/docs/asciidoc/CarePost-API.adoc
- server/src/main/java/com/Petching/petching/board/repository/BoardRepository.java
- server/src/main/java/com/Petching/petching/carepost/controller/CarePostController.java
- server/src/main/java/com/Petching/petching/carepost/dto/CarePostDto.java
- server/src/main/java/com/Petching/petching/carepost/mapper/CarePostMapper.java
- server/src/main/resources/static/docs/CarePost-API.html
- server/src/main/resources/static/docs/Comment-API.html
- server/src/main/resources/static/docs/JWT-API.html
- server/src/main/resources/static/docs/MyPet-API.html
- server/src/main/resources/static/docs/User-API.html
- server/src/main/resources/static/docs/index.html
- server/src/main/resources/static/docs/자랑하기-API.html
- server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
- server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
- CarePostController - MyPage API 테스트 코드를 작성했습니다.
- CarePostController - MyPage API 문서를 작성했습니다.
> [feat] CarePost - MyPage API 테스트 코드 및 문서 작성

- client/src/Components/User/MyPost.tsx
- client/src/Page/User.tsx
- MyPost 임의 구현
- 유저 페이지의 버튼 CSS 수정
> [feat] MyPost 임의 구현, 버튼 CSS 수정

- client/src/Components/Main/Explain.tsx
- client/src/Components/Main/Info.tsx
- client/src/Components/Main/MainMember.tsx
- client/src/Components/Main/MainPeacock.tsx
- 메인 페이지 컴포넌트 반응형 적용
- 멤버 정보 입력
> [design] Main 페이지 반응형 적용

- server/src/docs/asciidoc/CarePost-API.adoc
- server/src/docs/asciidoc/index.adoc
- server/src/main/resources/static/docs/CarePost-API.html
- server/src/main/resources/static/docs/Comment-API.html
- server/src/main/resources/static/docs/JWT-API.html
- server/src/main/resources/static/docs/MyPet-API.html
- server/src/main/resources/static/docs/S3-API.html
- server/src/main/resources/static/docs/User-API.html
- server/src/main/resources/static/docs/index.html
- server/src/main/resources/static/docs/자랑하기-API.html
- server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
- server/src/test/java/com/Petching/petching/restDocs/v1/login/LoginTest.java
- CarePostDto.Response에 postId 가 추가되었습니다.
- CarePost API 중 Delete가 문서에 추가되었습니다.
> [refactor] CarePost Dto 수정으로 인한 테스트 코드 수정 및 API 문서 반영

- client/src/Components/Main/Info.tsx
- client/src/Components/Main/MainMember.tsx
- 메인 섹션 배경이미지 추가
- 멤버 정보 수정 및 CSS 변경
> [design] 메인 배경 이미지 / 멤버 정보 수정

- client/src/Components/User/MyPost.tsx
- client/src/Hook/useGetMyPostToCare.ts
- 페이지 및 사이즈 변수 추가
- 작성한 게시글 조회 기능 구현
> [feat] 작성한 게시글(돌봄리스트)기능 구현

- client/src/Components/User/MyPost.tsx
- client/src/Components/User/PageBtns.tsx
- client/src/Hook/useGetMyPostToPeacock.ts
- client/src/Util/types.ts
- 작성글 조회에 사용되는 타입 명칭 변경 및 위치 변경 (useGetMyPostToCare => types)
- 자랑하기 게시글 조회 코드 작성 및 MyPost 적용
- 페이지네이션 버튼 컴포넌트화 분리
> [feat] 작성한 게시글(자랑하기) 조회 기능 임시 구현

- client/src/Components/User/MyLikes.tsx
- client/src/Hook/useGetUserLikes.ts
- client/src/Page/User.tsx
- 좋아요 게시글 조회 기능 구현(api 및 Card 컴포넌트 변경 필요)
- 좋아요한 게시글이 없을 경우 게시글 대신 안내 문구 출력
> [feat] 좋아요 게시글 조회 기능 (임시)구현

- client/src/Components/User/MyPost.tsx
- client/src/Components/User/PageBtns.tsx
- client/src/Components/User/UserInfo.tsx
- client/src/Layout/Header/GNB.tsx
- client/src/Layout/Header/Header.tsx
- client/src/Page/User.tsx
- 폰트 컬러 변경 적용 ( customHoverGreen => hoverGreen)
> [design] 변경된 컬러 적용

- client/src/Components/Inquery/SearchInput.tsx
- client/src/Components/User/UserInfo.tsx
- 회원정보 수정시 닉네임 중복확인 기능 구현
- 닉네임 변경을 진행했을 때 => 중복확인을 통과하지 못하면 수정완료가 안되도록 변경
- eslint 오류 수정
> [feat] 닉네임 중복확인 기능 구현

- client/src/Page/CareList.tsx
> [design] card 최대 3열로 제한

- client/src/Components/User/MyPost.tsx
- client/src/Util/navigateToCareListDetail.ts
- 작성한 게시글이 없는 경우 해당 알림 표시
- 훅을 함수 안으로 이동
> [feat] 작성한 게시글이 없을 경우 표시 기능 구현

- client/src/Components/Care/Card.tsx
- client/src/Components/User/MyLikes.tsx
- client/src/Components/User/MyPost.tsx
- client/src/Page/CareList.tsx
- client/src/Util/types.ts
- 돌봄리스트 데이터의 petSize => petSizes로 변경
> [fix] 데이터명 오류 수정

- client/src/Components/Care/Card.tsx
- client/src/Components/User/MyLikes.tsx
- client/src/Components/User/MyPost.tsx
- client/src/Page/CareList.tsx
- client/src/Util/types.ts
- Card 타입 변경(postId:number 추가)
- toCareListDetail 함수를 유틸에서 Card.tsx 내부로 이동(기존 파일 삭제는 진행하지 않음)
> [refactor] card 타입 변경 및 함수 이동

- client/src/Layout/Footer/Footer.tsx
- 푸터의 깃허브 버튼에 링크 연결
- 푸터 버튼에 hover 옵션 적용
> [feat] 깃허브 링크 연결

- client/src/Layout/Footer/Footer.tsx
- 문의하기 명칭 변경 => 고객센터
- 문의하기와 깃허브 버튼 UI 개선
> [design] 문의하기 명칭 변경, 디자인 수정

- server/src/docs/asciidoc/Board-API.adoc
- server/src/main/resources/application.yml
- server/src/main/resources/static/docs/CarePost-API.html
- server/src/main/resources/static/docs/Comment-API.html
- server/src/main/resources/static/docs/JWT-API.html
- server/src/main/resources/static/docs/MyPet-API.html
- server/src/main/resources/static/docs/S3-API.html
- server/src/main/resources/static/docs/User-API.html
- server/src/main/resources/static/docs/index.html
- server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
- server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
- 유저가 작성한 Board 게시물 조회 API 테스트 코드 작성
- 유저가 작성한 Board 게시물 조회 API 문서 작성
> [feat] 유저가 작성한 Board 게시물 조회 API 테스트 코드 작성 및 문서 작성

- client/src/Components/User/AddPet.tsx
- client/src/Components/User/PetCard.tsx
- client/src/Components/User/UserInfo.tsx
- client/src/Layout/Header/GNB.tsx
- GNB 와 유저 이미지, 펫 이미지에 'object-cover' 속성 추가
> [design] 이미지 속성 추가

- client/src/Components/Main/MainPeacock.tsx
> [design] MainPeacock 반응형 구현

- client/src/Components/Main/MainMember.tsx
- client/src/Components/Main/Members.tsx
> [feat] MainMember 반응형 구현

- server/src/main/java/com/Petching/petching/question/controller/QuestionController.java
- server/src/main/java/com/Petching/petching/question/dto/QuestionDto.java
- server/src/main/java/com/Petching/petching/question/entity/Question.java
- server/src/main/java/com/Petching/petching/question/mapper/QuestionMapper.java
- server/src/main/java/com/Petching/petching/question/repository/QuestionRepository.java
- server/src/main/java/com/Petching/petching/question/service/QuestionService.java
> [feat] question crud

- client/src/Components/Care/ImageUploader.tsx
- client/src/Page/CareListPost.tsx
> [refactor] CareListPost에서 Upload버튼 제거

- client/package-lock.json
- client/package.json
- client/src/API/api.ts
- client/src/Components/Care/TextEditor.tsx
- client/src/Page/InqueryWrite.tsx
- client/src/Page/peacockWrite.tsx
1. peacock 자랑하기 textEditor 기준으로 구현 완료했습니다. 문의하기 api쪽은 추후 수정 예정입니다.
2. editor markdown 모드로 고정시켜놓았습니다.
> [feat]TextEditor Img, Content 기능구현

- client/src/Components/Care/PeacockTextEditor.tsx
- client/src/Page/peacockWrite.tsx
> [fix]배포오류 수정

- client/src/Components/Care/Card.tsx
- client/src/Components/Care/Carousel.tsx
- client/src/Page/CareListDetail.tsx
<Carousel imgUrls={imgUrls} width="30rem" height="80" /> 와 같이 string으로 전달합니다
> [feat] Carousel width height 페이지에 맞게 변경

- client/src/Page/CareListDetail.tsx
CareListDetail 페이지 기본배치 변경, 버튼색 변경을 했습니다
> [design] CareListDetail css 디자인 1차

- client/src/Components/Main/MainMember.tsx
> [refactor] 멤버 타이틀 추가

- server/src/main/java/com/Petching/petching/board/controller/BoardController.java
- server/src/main/java/com/Petching/petching/board/entity/Board.java
- server/src/main/java/com/Petching/petching/board/service/BoardService.java
- server/src/main/java/com/Petching/petching/user/entity/User.java
- server/src/main/resources/static/docs/CarePost-API.html
- server/src/main/resources/static/docs/Comment-API.html
- server/src/main/resources/static/docs/JWT-API.html
- server/src/main/resources/static/docs/MyPet-API.html
- server/src/main/resources/static/docs/S3-API.html
- server/src/main/resources/static/docs/User-API.html
- server/src/main/resources/static/docs/index.html
: 요청 보낼 시 유저가 좋아요를 눌러놨는지 검사 후 결과에 따라 맞게 수정
> [refactor] board 좋아요 받는 방식 수정

- client/src/Components/Care/Card.tsx
- client/src/Components/Care/Postcode.tsx
- client/src/Components/Care/ReactCalendar.tsx
- client/src/Page/CareList.tsx
* input창이 작아서 키웠습니다
* z-index문제로 carousel이 postcode보다 위에 있던 버그를 수정했습니다
> [design] carelist 페이지 input 디자인

- client/src/Components/Care/ImageUploader.tsx
- client/src/Hook/useDateSelect.ts
- client/src/Page/CareList.tsx
- client/src/Page/CareListPost.tsx
CareListPost 파일 디자인 
+ Hook 사용
> [design] CareListPost 파일 디자인

- client/src/Page/CareListPost.tsx
> [feat] 게시 누르면 carelist로 이동

- server/src/main/java/com/Petching/petching/board/controller/BoardController.java
- server/src/main/java/com/Petching/petching/temp/chat/config/WebSocketConfig.java
- server/src/main/java/com/Petching/petching/temp/chat/service/ChatService.java
- server/src/main/java/com/Petching/petching/user/service/UserService.java
- Board 게시물 좋아요 누를 시 제대로 작동하지 않았던 것을 fix 했습니다.
> [bug][fix] board 글 수정 bug fix

- server/src/main/generated/com/Petching/petching/board/mapper/BoardMapperImpl.java
- server/src/main/generated/com/Petching/petching/carepost/mapper/CarePostMapperImpl.java
- server/src/main/generated/com/Petching/petching/comment/mapper/CommentMapperImpl.java
- server/src/main/generated/com/Petching/petching/user/mapper/UserMapperImpl.java
- server/src/main/resources/static/docs/Board-API.html
- server/src/main/resources/static/docs/CarePost-API.html
- server/src/main/resources/static/docs/Comment-API.html
- server/src/main/resources/static/docs/JWT-API.html
- server/src/main/resources/static/docs/MyPet-API.html
- server/src/main/resources/static/docs/Question-API.html
- server/src/main/resources/static/docs/S3-API.html
- server/src/main/resources/static/docs/User-API.html
- server/src/main/resources/static/docs/index.html
- server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
- server/src/test/java/com/Petching/petching/restDocs/global/mock/StubData.java
-  CarePost-api 에 대한 테스트 코드 수정 및 API 문서화 하였습니다.
> [fix] CarePost-api 에 대한 테스트 코드 수정 및 API 문서화

- client/src/Page/CareListDetail.tsx
> [feat] userId === postUserId 이면 수정하기 버튼추가

- client/src/Page/CareList.tsx
- client/src/Page/CareListDetail.tsx
- client/src/Page/CareListPost.tsx
- client/src/store/editPost.ts
수정기능작동 확인했습니다.
아직 이미지기존값 가져오기, 가끔뜨는 500에러 원인은 못찾았습니다.
> [feat] 돌봄리스트 게시물 수정기능 추가

- client/src/Page/CareList.tsx
주소, 날짜부분에 md 크기의 반응형디자인을 적용했습니다
> [design] CareList 반응형 디자인 적용
